### ISSUE TITLE
Error while parsing byte count

### ISSUE THREAD

**Issue by voidd** [mash/go-intelhex#3]
"ByteCount expected but got something else"

with such strings as examples:

:FB008700412F0042434D343331343241302047656E657269632055534220436C6173732032204E6F6E5548452040203230204D487A00980100035C01000172060003000708000193040020000000920600A300C80014648F0300020202B209000000008000000000006F210002331F05CF000000AA147F8C00AA00800A9200000000140000000000006C584E6C6A3600018011000000B0000000A0000000420000005200000080000000900000006200000072000000C1000000D000000022000000320000007C0400010A00020A05001C0A200001C408007800320000030000C30000C0000698F83100FFFFFFFFFF7F00009CF83100FFFFFFFF083B0000A03A

:8700000001060069999942041FC15E00000014222200001422223B02570258025802590259025A025A025B025B025C025C025D025D025E025E025F025F02600260026102610262026202630263026402640265026502660266026702670268026802690269026A026A026B281F0AFD0400FFFFFFFF400600937600A40100020A0087002100000000000000FA

**Comment by mash** [comment]
Thanks
